name: audio_exif
description: A dart package that retrieves metadata from audio files.
version: 1.0.0+1
repository: https://github.com/simranss/dart_audio_exif

environment:
  sdk: ^3.3.4

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
